### ISSUE TITLE
New 3.5.5 version

### ISSUE THREAD

**Issue by Machou** [portapps/teamspeak-client-portable#21]
Hello

New version of TeamSpeak 👍 

```
=== Client Release 3.5.5 - 04 Nov 2020

Fixed crash in the comfort noise algorithm
Fixed crash in audio processing (reported by Stefan Schiller (scryh))
```

https://community.teamspeak.com/t/teamspeak-3-client-3-5-5/13040
https://www.teamspeak.com/en/downloads/

**Comment by crazy-max** [comment]
https://portapps.io/news/2020-12-19-teamspeak-client-portable-3.5.6-18/
